name: CI build docker action
on:
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@Israel'
      - name: Output time set in container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
